---
- name: Install Ruby 2.7
  hosts: beezwax
  remote_user: deploy
  become: yes
  tasks:
    - name: Check if Ruby is installed
      command: which ruby
      register: ruby_check
      ignore_errors: yes
